global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-server'
    static_configs:
      - targets: [
          #'app-server:3000', 
          'horz-scaled-app-app-server-1:3000', 
          'horz-scaled-app-app-server-2:3000',
          'horz-scaled-app-app-server-3:3000', 
          'horz-scaled-app-app-server-4:3000',
        ]
    metrics_path: metrics
    scheme: http

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:7000']
    metrics_path: metrics
    scheme: http
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  