global:
  scrape_interval: 1s

scrape_configs:
  # - job_name: 'nginx exporter'
  #   static_configs:
  #     - targets: ['nginx-prometheus-exporter:9113']
  #   metrics_path: metrics
  #   scheme: http

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']  # Replace with the actual address of your NGINX server
    metrics_path: metrics
    scheme: http

  - job_name: 'app-server'
    static_configs:
      - targets: [ 
          'app-server-1:3000', 
          'app-server-2:3001', 
          'app-server-3:3002', 
          'app-server-4:3003',
        ]
    metrics_path: metrics
    scheme: http

  - job_name: 'consumer'
    static_configs:
      - targets: [
        'consumer-1:7000',
        'consumer-2:7001',
        'consumer-3:7002',
        'consumer-4:7003',
        ]
    metrics_path: metrics
    scheme: http
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  