version: '3.2'
services:
  server:
    container_name: crud-server
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 80:3000
    cpus: '1.0'
    mem_limit: 200m
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
    depends_on:
      - db

  db:
    container_name: crud-db
    image: postgres:14.1-alpine
    cpus: '1.0'
    mem_limit: 500m
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:${POSTGRES_VOLUME}

volumes:
  db:
    driver: local