{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "App Server % CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name='app-server'}[1m])) by (name) * 100",
     "legendFormat": "App Server % CPU Usage"
    }
   ]
  },
  {
   "title": "App Server % Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{name=\"app-server\"} / container_spec_memory_limit_bytes{name=\"app-server\"})) by (name) * 100",
     "legendFormat": "App Server % Memory Usage"
    }
   ]
  },
  {
   "title": "App Server RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_server_histogram_request_duration_seconds_count{route!=\"/metrics\"}[1m])) by (route)",
     "legendFormat": "App Server RPS"
    }
   ]
  },
  {
   "title": "App Server P90 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_server_histogram_request_duration_seconds_bucket{route!=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "DB % CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"crud-db\"}[1m])) by (name) * 100",
     "legendFormat": "DB % CPU Usage"
    }
   ]
  },
  {
   "title": "DB % Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{name=\"crud-db\"} / container_spec_memory_limit_bytes{name=\"crud-db\"})) by (name) * 100",
     "legendFormat": "App Server % Memory Usage"
    }
   ]
  }
 ]
}