{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "App Server Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{image=\"horz-scaled-app-app-server\"}[1m])) by (name) * 100",
     "legendFormat": "App Server % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{image=\"horz-scaled-app-app-server\"} / container_spec_memory_limit_bytes{image=\"horz-scaled-app-app-server\"})) by (name) * 100",
     "legendFormat": "App Server % Memory Usage"
    }
   ]
  },
  {
   "title": "Consumer Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{image=\"horz-scaled-app-consumer\"}[1m])) by (name) * 100",
     "legendFormat": "Consumer % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{image=\"horz-scaled-app-consumer\"} / container_spec_memory_limit_bytes{image=\"horz-scaled-app-consumer\"})) by (name) * 100",
     "legendFormat": "Consumer % Memory Usage"
    }
   ]
  },
  {
   "title": "DB Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"crud-db\"}[1m])) by (name) * 100",
     "legendFormat": "DB % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{name=\"crud-db\"} / container_spec_memory_limit_bytes{name=\"crud-db\"})) by (name) * 100",
     "legendFormat": "DB % Mem Usage"
    }
   ]
  },
  {
   "title": "Cache Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"cache\"}[1m])) by (name) * 100",
     "legendFormat": "Cache % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{name=\"cache\"} / container_spec_memory_limit_bytes{name=\"cache\"})) by (name) * 100",
     "legendFormat": "Cache % Memory Usage"
    }
   ]
  },
  {
   "title": "Queue Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"queue\"}[1m])) by (name) * 100",
     "legendFormat": "Queue % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{name=\"queue\"} / container_spec_memory_limit_bytes{name=\"queue\"})) by (name) * 100",
     "legendFormat": "Queue % Mem Usage"
    }
   ]
  },
  {
   "title": "Consumption Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(consumer_load_gauge{job=\"app-server\"})",
     "legendFormat": "Messages on Queue"
    },
    {
     "expr": "sum(abs(consumer_load_gauge{job=\"consumer\"}))",
     "legendFormat": "Messages consumed from Queue"
    }
   ]
  },
  {
   "title": "App Server RPS (Host)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(app_server_histogram_request_duration_seconds_count{route!=\"/metrics\"}[1m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Server P90 Response Time (Host)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_server_histogram_request_duration_seconds_bucket{route!=\"/metrics\"}[1m])) by (le, host))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Reverse Proxy Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{image=\"horz-scaled-app-reverseproxy\"}[1m])) by (name) * 100",
     "legendFormat": "Reverse Proxy % CPU Usage"
    },
    {
     "expr": "sum((container_memory_usage_bytes{image=\"horz-scaled-app-reverseproxy\"} / container_spec_memory_limit_bytes{image=\"horz-scaled-app-reverseproxy\"})) by (name) * 100",
     "legendFormat": "Reverse Proxy % Mem Usage"
    }
   ]
  }
 ]
}