{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "App Server % CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{image=\"simple-app-app-server\"}[1m])) * 100",
     "legendFormat": "% CPU Usage"
    }
   ]
  },
  {
   "title": "App Server % Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{image=\"simple-app-app-server\"} / container_spec_memory_limit_bytes{image=\"simple-app-app-server\"})) by (name) * 100",
     "legendFormat": "% Memory Usage"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_server_histogram_request_duration_seconds_count{route!=\"/metrics\"}[2s]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "P90 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_server_histogram_request_duration_seconds_bucket{route!=\"/metrics\"}[2s])) by (le))",
     "legendFormat": "P90"
    }
   ]
  }
 ]
}